name: vps-monitor

services:
  vps-monitor:
    build: ../app
    container_name: vps-monitor
    restart: unless-stopped
    ports:
      - "127.0.0.1:3020:3000"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/www:/var/www
      - /etc/nginx:/etc/nginx:ro
      - /etc/nginx/sites-available:/etc/nginx/sites-available
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
    env_file:
      - path: ../.env
        required: false
    environment:
      PORT: "3000"
      BASE_URL: "http://78.138.58.95"
      NGINX_CONFIG: /etc/nginx/sites-available/vps
      VPSCONFIG_PATH: /var/www/vps-monitor
